feat(queue): add retryAllFailedJobs method
taskforcesh/bullmq pull request #1024
Opened 2022-01-26 03:00 UTC by roggervalf

2022-01-26 03:00 UTC, roggervalf commented on src/classes/queue.ts
> +  async retryAllFailedJobs(count?: number): Promise<void> {
probable we could rename this as retryFailedJobs, to be shorter :thinking:

2022-01-26 04:19 UTC, manast requested changes

2022-01-26 04:19 UTC, manast commented on src/commands/retryAllFailedJobs-4.lua
> +  if (rcall("ZREM", KEYS[3], key) == 1) then
It should not be needed to check that we in fact removed the value from the zset since .lua scripts are atomic and we got the value from a previous call to ZRANGE. By skipping this test we can remove the values much faster in one call (up to 7000 values since there is an issue with more than 8k values in Redis), check how we did it here: https://github.com/taskforcesh/bullmq/blob/master/src/commands/moveStalledJobsToWait-8.lua#L103-L107
Same concept can be applied to LPUSH, however not possible with HDEL and HSET. I think the reset of finishOn, etc could be made when moving the job to active so that it is done lazily and therefore this call will become much faster, what do you think?
Also, regarding attemptsMade, I see there is a point in resetting it, but not sure we must, that would also make this call faster as we do not need to iterate through all the keys one by one.

2022-01-26 04:19 UTC, manast commented on src/commands/retryAllFailedJobs-4.lua
> +  if (rcall("ZREM", KEYS[3], key) == 1) then
Sadly we cannot optimize the call to XADD, so that will still need to be iterated...

2022-01-26 04:19 UTC, manast commented on src/classes/queue.ts
> +  async retryAllFailedJobs(count?: number): Promise<void> {
the minimal name would be just "retryFailed", or even just "retry" if in the future we would allow retry also "completed" jobs, which is not completely unlikely, the case being, a lot of jobs completed but they did not do the proper job, so we want to retry all of them.

2022-01-26 04:19 UTC, manast commented on src/classes/queue.ts
> +  async retryAllFailedJobs(count?: number): Promise<void> {
maybe "retryJobs" then.

2022-01-26 04:19 UTC, manast commented on tests/test_queue.ts
> +      await queue.retryAllFailedJobs(2);
It is also important to check that the order of the retried jobs is correct, as the oldest failed must be the first to be retried.

2022-01-26 04:20 UTC, manast commented
Note: we need to backport this feature to Bull aswell.

2022-01-26 13:19 UTC, roggervalf commented on src/classes/queue.ts
> +  async retryAllFailedJobs(count?: number): Promise<void> {
sounds good to me, I will change the count prop to be into an object, so when we introduce the case for completed jobs, a new param could be place into this object

2022-01-26 14:32 UTC, manast commented on src/commands/retryJobs-4.lua
> +return 0
Notice that there is no newline at the end.

2022-01-28 05:41 UTC, manast reviewed
Looks great, just a small comment regarding the documentation of the retryAll method.

2022-01-28 05:41 UTC, manast commented on src/classes/queue.ts
> +  async retryJobs(opts: { count?: number } = {}): Promise<void> {
We should add a documentation snippet for this method so that it appears in the API documentation.

2022-01-28 05:41 UTC, manast commented on src/commands/includes/batches.lua
> +local function batches(n, batchSize)
Nice refactoring

2022-01-28 05:41 UTC, manast commented on src/commands/retryJobs-4.lua
> +if (#jobs > 0) then
This "if" can also be moved to include also the "ipairs" loop

2022-01-28 05:41 UTC, manast commented on src/commands/retryJobs-4.lua
> +  for from, to in batches(#jobs, 7000) do
Very nice

2022-01-29 04:39 UTC, manast approved these changes

2022-01-29 14:52 UTC, merged