feat(job): add queueName to JobJson
taskforcesh/bullmq pull request #1051
Opened 2022-02-04 18:34 UTC by jgillick

Added queueName to the JobJson type so that it will be available to sandboxed workers.

In response to [#1050](https://github.com/taskforcesh/bullmq/issues/1050)

2022-02-04 19:30 UTC, roggervalf reviewed
LGTM, just some minor comments

2022-02-04 19:30 UTC, roggervalf commented on src/interfaces/job-json.ts
> +  queueName?: string;
I think ? is not needed, queueName should be always present

2022-02-04 19:30 UTC, roggervalf commented on src/classes/job.ts
> +      queueName: this.queueName,
you could modify one of the sandbox test cases to consider this change too

2022-02-05 00:03 UTC, jgillick commented
Thanks @roggervalf. I created an entirely new sandbox unit test for this.

2022-02-05 04:29 UTC, manast requested changes
Thanks for the PR. 
Unfortunatelly, and I do not want to be a party pooper :), but we cannot store the queueName in the job structure, since this will take a lot of Redis memory and most importantly it should not be needed. Instead we have to implement it here: https://github.com/taskforcesh/bullmq/blob/master/src/classes/child-processor.ts#L127
Since the original Job class already has a getter that returns the queueName:
https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L544

2022-02-07 03:13 UTC, roggervalf commented
Thanks @manast, sorry @jgillick but currently asJSON method is used in https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L893, so it would be saved in redis, we should not save queueName as it is a getter as mentioned above. I can take this feature on my own for this changes.

2022-02-08 14:22 UTC, closed without merging

2022-02-08 17:54 UTC, jgillick commented
All good. I'll refactor it this week or next. Thank you.

2022-02-08 19:53 UTC, jgillick commented
@roggervalf This works. Thank you!