Get jobs enhancements
taskforcesh/bullmq pull request #1113
Opened 2022-03-02 10:35 UTC by Toilal

See https://github.com/taskforcesh/bullmq/issues/1112

2022-03-10 10:32 UTC, ATheCoder commented
@manast

2022-03-11 04:26 UTC, manast approved these changes

2022-03-11 04:39 UTC, roggervalf requested changes

2022-03-11 04:39 UTC, roggervalf commented on src/classes/queue-getters.ts
> +        sanitizedTypes.indexOf('waiting-children')
we are not considering paused when waiting-children is provided in the current master branch, you could update your branch with master

2022-03-11 04:39 UTC, roggervalf commented on src/classes/queue-getters.ts
> +    if (typeof types === 'string') {
what about:
`const currentTypes = typeof types === 'string' ? [types] : types;`

2022-03-11 07:13 UTC, Toilal commented on src/classes/queue-getters.ts
> +    if (typeof types === 'string') {
Il would create `[undefined]` array if parameter is undefined

2022-03-11 07:21 UTC, Toilal commented on src/classes/queue-getters.ts
> +        sanitizedTypes.indexOf('waiting-children')
I have removed `sanitizedTypes.indexOf('waiting-children')` from this condition

2022-03-11 07:23 UTC, Toilal commented on src/classes/queue-getters.ts
> +    return this.getJobCountByTypes('waiting', 'delayed', 'waiting-children');
I'm not sure if 'paused' should be removed here

2022-03-11 08:31 UTC, manast commented on src/classes/queue-getters.ts
> +    return this.getJobCountByTypes('waiting', 'delayed', 'waiting-children');
It should not be removed. When the queue is paused what happens is that the wait key gets renamed to "paused", but other than that the status of a job is still waiting.

2022-03-11 08:35 UTC, Toilal commented on src/classes/queue-getters.ts
> +    return this.getJobCountByTypes('waiting', 'delayed', 'waiting-children');
Thanks, I have rollbacked this method.

2022-03-12 01:24 UTC, roggervalf commented on src/classes/queue-getters.ts
> +    if (typeof types === 'string') {
hey @Toilal, but if types is `undefined`, `typeof types === 'string'` would be `false`, in that case currentTypes will be `undefined`, not `[undefined]` :thinking:

2022-03-14 07:06 UTC, Toilal commented on src/classes/queue-getters.ts
> +    if (typeof types === 'string') {
Ho yes my mistake, I have updated the PR :)

2022-03-15 00:17 UTC, roggervalf approved these changes
LGTM

2022-03-15 01:22 UTC, merged