feat(worker): change the number of concurrent processes
taskforcesh/bullmq pull request #1256
Opened 2022-05-24 03:23 UTC by roggervalf

ref https://github.com/taskforcesh/bullmq/issues/22

2022-05-26 03:37 UTC, manast requested changes

2022-05-26 03:37 UTC, manast commented on src/classes/worker.ts
> +    this.opts = { ...this.opts, concurrency };
why not simply ```this.opts.concurrency = concurrency```

2022-05-26 03:37 UTC, manast commented on src/classes/worker.ts
> +              if (getNextJob) {
I do not think this is correct. We only push the token back to the tokens array when there are no new jobs to process right now so that this same token can be reused in the future. It is not related to if we called getNextJob or not.

2022-05-26 03:37 UTC, manast commented on src/classes/worker.ts
> +                    this.processJob(job, token, processing.size <= concurrency),
The problem here is that ```processing.size <= concurrency``` could be true or false at the time we call ```processJob```, however at the time we use the boolean ```fetchNext``` inside ```processJob``` the assertion may not be true or false anymore.

2022-05-26 04:02 UTC, roggervalf commented on src/classes/worker.ts
> +              if (getNextJob) {
yes, but in this case I'm considerong when we decrease the concurrencia, so tokens should decrease as well

2022-05-26 07:02 UTC, manast commented on src/classes/worker.ts
> +              if (getNextJob) {
Yes but you have asynchronous calls in between (line 363), so the "getNextJob" flag may not represent the same thing anymore at this point in the code, since the concurrency could have changed.

2022-05-26 13:07 UTC, roggervalf commented on src/classes/worker.ts
> +    this.opts = { ...this.opts, concurrency };
this is because opts is a public attribute, in order to not affect external references is better to use this spread operator

2022-05-26 13:09 UTC, roggervalf commented on src/classes/worker.ts
> +                    this.processJob(job, token, processing.size <= concurrency),
you are right, now I'm considering using a callback function

2022-05-27 03:37 UTC, manast commented on src/classes/worker.ts
> +    this.opts = { ...this.opts, concurrency };
If that is the case, then we should copy opts already in the constructor, because otherwise if the user modifies "opts" outside of bull it would affect the worker's behaviour as a side effect.

2022-05-28 04:34 UTC, manast commented on src/classes/worker.ts
> +                      () => processing.size <= concurrency,
here we need to use this.opts.concurrency, since the concurrency level could have been changed since it was assigned to the variable concurrency in line 375. I also think it is not needed to assing to a local concurrency variable, we can just use this.opts.concurrency.

2022-05-30 03:56 UTC, manast approved these changes

2022-05-30 04:14 UTC, merged