fix(job): avoid error when job is moved when processing
taskforcesh/bullmq pull request #1354
Opened 2022-08-10 01:00 UTC by roggervalf

fixes https://github.com/taskforcesh/bullmq/issues/1343

2022-09-01 17:45 UTC, loris commented
Any update on this one? @manast

2022-09-05 11:17 UTC, manast commented
@loris this PR does not fix the issue unfortunatelly.

2022-09-22 07:59 UTC, manast approved these changes
Crazy, I thought this change was already in 2.0

2022-09-22 08:02 UTC, manast requested changes
We need some documentation on the new arguments and behaviour.

2022-09-23 09:04 UTC, manast commented
Ok, so a couple of things:
- I think the autoComplete should be a job setting, not an argument for delay. The reason is that we may want to use this feature for other things. For example, rate-limiter, if you detect in the process function that you want this job to rate limit, then you can just explicitly activate the limit, move the job back to wait and then set the autoComplete to false.
- We need to explain what the autoComplete do in the documentation (simply that by default jobs complete as soon as they finalize, but you can disable this behaviour by disabling autoComplete, which is useful for doing this and that. :).
- I do not think the autoComplete setting needs to be stored in the job persistently, it could just be a property of the Job instance.
-

2022-10-28 15:50 UTC, neighbaa commented
This looks like a great feature and I'm looking forward to this update, but I noticed something - couldn't this pattern also affect or break backoff / retries?
Presumably, when the job resumes it will increase attemptsMade - if the job then throws an error, wouldn't the backoff function use the same number?

If that's the case, I guess attemptsMade could possibly be decremented whenever the job is moved while processing. Should that also be done manually, or should it happen by default if you use autoComplete?

If that's not the case, apologies for an unhelpful comment.

Cheers

2022-10-28 16:03 UTC, manast commented on docs/gitbook/patterns/process-step-jobs.md
> +            job.autoComplete = true; // prevent missing lock error
I think you are right, the default must be auto-complete which is the current behavior.

2022-10-28 16:03 UTC, manast commented on src/classes/job.ts
> +  autoComplete: boolean = false;
I agree, it should be true here.

2022-10-28 16:07 UTC, manast commented
@neighbaa which use-case are you planing to implement if this PR gets merged?

2022-10-28 17:02 UTC, neighbaa commented
> @neighbaa which use-case are you planing to implement if this PR gets merged?

I'll try and explain. Bearing in mind, I could be wrong about how attemptsMade works, or when it gets incremented.

I'm imagining this being a problem in a case where I conditionally create child jobs from a parent processor and call moveToWaitingChildren. Say the parent job has the exponential backoff strategy set with 10 attempts.
When the parent resumes, it is possible the condition will still be met to once again create new child jobs and call moveToWaitingChildren.

This could happen x number of times.
If x is 7, and then for some reason an error throws inside the parent processor, even if it's the first error, would the retry delay be set to 2 ^ 7 * delay ?
If x is already more than 10, would the job simply fail, or not retry?

I imagine it's the same for repeatedly delaying jobs on condition. (Possibly if I'm polling another service or something.)

I might be wrong, but I would have expected that even if the job has run 10 times already, the first error should follow the backoff strategy with attemptsMade = 1 and retry promptly.

Does this make sense?

2022-12-27 05:45 UTC, roggervalf commented on tests/test_rate_limiter.ts
> -        workerDelay: true,
workerDelay option does not exist in our code base

2023-03-22 14:18 UTC, manast approved these changes

2023-03-22 23:10 UTC, merged