fix(job): fetch parent before job moves to complete
taskforcesh/bullmq pull request #1580
Opened 2022-12-09 10:56 UTC by S3bb1

When creating a flow with a long-running job in the beginning (e.g. takes multiple seconds) and during the processing of the job you want to add a new parent to this job (because it should run after the long-running job) it doesn't execute the job which was added after.

The root cause of this issue is, that the worker fetches the `Job` from redis before it moves it to active. When the `Job` then finishes, the worker passes the previous fetched instance of the job to `moveToCompleted`. When an additional Job is added as `parent` of the current processing job, it gets never executed because the instance don't have the correct parent key. 

This PR adds an additional "sync" of the parent key of the job before it gets moved to completed to have the current instance up to date when in the meantime a new parent was added. 

Added a test which runs the following flow:

- Create Job 1 without children
  - Flow moves Job to active
  - Worker processes job (wait 1000ms)
- Client waits 500ms
- Client adds new Job 2 with children [Job1]
- Worker finishes Job 1
- Worker starts Job 2 
- Worker finishes Job 2

2022-12-13 02:40 UTC, roggervalf commented on src/classes/job.ts
> +    const jobData = await Job.fromId(this.queue, this.id);
better to handle this logic atomically in moveToFinished script, so probably we may need to get parent values from there instead of providing it in args

2022-12-13 07:19 UTC, S3bb1 commented on src/classes/job.ts
> +    const jobData = await Job.fromId(this.queue, this.id);
Added the fetch of the parent and the parentKey into the lua scripts.

2022-12-15 05:32 UTC, S3bb1 commented
Can we rerun the tests? On my local machine they went through

2022-12-15 08:51 UTC, manast requested changes

2022-12-15 08:51 UTC, manast commented on src/commands/moveToFinished-12.lua
> -    local parentId = opts['parent'] and opts['parent']['id'] or ""
Since we are not using opts['parent'] nor opts['parentKey'] anymore, we should also remove them from the opts object passed to the script to avoid passing unnecessary data in the Redis call.

2022-12-15 09:32 UTC, S3bb1 commented on src/commands/moveToFinished-12.lua
> -    local parentId = opts['parent'] and opts['parent']['id'] or ""
Thanks! That makes sense :) removed the lines in the `moveToFinishedArgs` function

2022-12-15 09:49 UTC, manast approved these changes

2022-12-20 04:06 UTC, S3bb1 commented
Any updates here @roggervalf?

2022-12-20 22:59 UTC, roggervalf approved these changes
Sorry for the delay, LGTM

2022-12-20 23:00 UTC, merged