feat(worker): getter for a concurrency
taskforcesh/bullmq pull request #2883
Opened 2024-11-05 11:01 UTC by fgozdz

2024-11-05 14:11 UTC, manast approved these changes
LGTM

2024-11-05 14:30 UTC, roggervalf requested changes

2024-11-05 14:30 UTC, roggervalf commented on src/classes/worker.ts
> +    return this.opts.concurrency;
I think this is a bug where this.opts.concurrency should not be set, instead it should be this.concurrency = concurrency at line 395. opts should be immutable as we threat other options like priority or delay. If you change that line, this getter may not be needed

2024-11-05 14:39 UTC, fgozdz commented on src/classes/worker.ts
> +    return this.opts.concurrency;
This is resulting in unending recursion: "RangeError: Maximum call stack size exceeded"

2024-11-05 15:22 UTC, fgozdz commented
This issue fixes #2880

2024-11-05 21:14 UTC, manast commented on src/classes/worker.ts
> +    return this.opts.concurrency;
@fgozdz what @roggervalf means is that we should not replace this.opts.concurrency as this is mutating the opts object which was passed in the constructor. Instead you can define a private property like _concurrency, and use this instead of this.opts.concurrency. In the constructor you set _concurrency to a default value if this.opts.concurrency is not defined.

2024-11-05 21:15 UTC, manast commented on src/classes/worker.ts
> +    return this.opts.concurrency;
Honestly speaking It would be far mote elegant to have a explicit setter like "setConcurrency" instead of an implicit setter, but this would imply a breaking change, so we cannot do that now.

2024-11-06 03:45 UTC, roggervalf commented on src/classes/worker.ts
> +    return this.opts.concurrency;
@fgozdz you can try doing:
```js
set concurrency(concurrency: number) {
    if (
      typeof concurrency !== 'number' ||
      concurrency < 1 ||
      !isFinite(concurrency)
    ) {
      throw new Error('concurrency must be a finite number greater than 0');
    }
    this._concurrency = concurrency;
  }

  get concurrency(): number {
    return this._concurrency;
  }

```
on worker constructor you may need to replace https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L241 as:
`this._concurrency = this.opts.concurrency;
`
and add a private attribute type after this one https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L182 like:
`private _concurrency:number;
`
also in order to use this new attribute you should replace this.opts.concurrency to use this._concurrency at worker level

2024-11-07 14:16 UTC, roggervalf approved these changes
Lgtm, thank you

2024-11-08 02:16 UTC, merged