fix(docs): provide connection details in getting started (fixes #2847)
taskforcesh/bullmq pull request #2897
Opened 2024-11-12 12:55 UTC by fgozdz

This issue fixes #2847

2024-11-12 13:13 UTC, manast approved these changes
LGTM

2024-11-12 13:30 UTC, roggervalf requested changes

2024-11-12 13:30 UTC, roggervalf commented on docs/gitbook/guide/connections.md
> +const connection = new IORedis({ maxRetriesPerRequest: null });
something to take in count is that we are recommending to not ass this option for producers (Queue), only for consumers (Workers). Pls change it to reflect it base on https://docs.bullmq.io/bull/patterns/persistent-connections#queue

2024-11-29 14:29 UTC, roggervalf approved these changes
Lgtm

2024-12-02 21:47 UTC, manast approved these changes

2024-12-07 04:49 UTC, merged