test(job-scheduler): add tests covering job retries and stalls
taskforcesh/bullmq pull request #2941
Opened 2024-11-27 16:52 UTC by manast

2024-11-28 02:03 UTC, roggervalf commented on tests/test_job_scheduler.ts
> +      const lockKey = `bull:${queueName}:${repeatableJob!.id}:lock`;
${prefix} is missing as dragonfly requires it for tests to pass

2024-11-28 02:03 UTC, roggervalf commented on tests/test_job_scheduler.ts
> +      const stalledCheckerKey = `bull:${queueName}:stalled-check`;
same as above

2024-11-28 11:01 UTC, fgozdz requested changes

2024-11-28 11:01 UTC, fgozdz commented on tests/test_job_scheduler.ts
> +  describe('when repeatable job fails', async function () {
describe should not be async: https://mochajs.org/#limitations-of-asynchronous-callbacks

2024-11-28 14:18 UTC, manast commented
Thanks for the comments, I addressed all of them.

2024-11-29 05:04 UTC, roggervalf commented on tests/test_queue.ts
> +        connection,
prefix is missing to be passed

2024-12-02 16:44 UTC, roggervalf approved these changes

2024-12-02 16:47 UTC, merged