docs: add doc for bebounce usecase
taskforcesh/bullmq pull request #335
Opened 2020-12-11 16:54 UTC by Valtena

Hi,

This days, I have search to debounce job with same Id in queue to avoid run multiple time an heavy computation. I didn't found this function here. I have fork project to implement this before see that it's already implemented. So i have tried to add a little example to doc this functionality.

2020-12-21 08:53 UTC, manast commented on docs/gitbook/patterns/debounce-jobs.md
> +Sometimes, you want to update data in reactions of a sequence of events instead at each event.
I am not native english but I think "of a" -> "to a"

2020-12-21 08:54 UTC, manast commented on docs/gitbook/patterns/debounce-jobs.md
> +That override the job ID - by default, the job ID is a unique
overrides

2020-12-21 08:54 UTC, manast commented on docs/gitbook/patterns/debounce-jobs.md
> +That override the job ID - by default, the job ID is a unique
a unique number ->an increasing counter

2020-12-21 08:56 UTC, manast commented on docs/gitbook/patterns/debounce-jobs.md
> +already exists, it will not be added.
Hint: Be careful if using removeOnComplete/removeOnFailed options, since a removed job will not count as existing and a new job with the same job Id would indeed be added to the queue.

2020-12-21 08:57 UTC, manast requested changes
I wrote some comments

2020-12-22 16:42 UTC, Valtena commented on docs/gitbook/patterns/debounce-jobs.md
> +That override the job ID - by default, the job ID is a unique
For `a unique integer ->an increasing counter`, I have a question. I pick this part in comm from `src/interfaces/jobs-options.ts` l 37. The comm in file is outdated  or need the same patch?

2021-01-30 17:01 UTC, airhorns commented
Would be great to get this in -- really handy feature but you have to know the trick to use `jobId` so I think this documentation would really help!

2021-01-31 09:56 UTC, merged