Fix getJobLogs no reversed pagination
taskforcesh/bullmq pull request #538
Opened 2021-05-10 03:07 UTC by roggervalf

2021-05-16 09:19 UTC, manast commented
Thanks for the PR. I guess it comes from this issue https://github.com/OptimalBits/bull/issues/2031
As I wrote, I think the best would be to introduce an "asc" parameter as we have in the other getters where default would be "false" so that we keep backwards compatibility since there are cases were we want to paginate from newest logs to oldest and others when we want to provide streaming.

2021-05-16 22:28 UTC, roggervalf commented
> Thanks for the PR. I guess it comes from this issue [OptimalBits/bull#2031](https://github.com/OptimalBits/bull/issues/2031)
> As I wrote, I think the best would be to introduce an "asc" parameter as we have in the other getters where default would be "false" so that we keep backwards compatibility since there are cases were we want to paginate from newest logs to oldest and others when we want to provide streaming.

Sure, in last version I refactored it. Thanks

2021-05-17 01:13 UTC, tjhiggins requested changes

2021-05-17 01:13 UTC, tjhiggins commented on src/classes/queue-getters.ts
> +    if (asc) {
Shouldn't this be flipped for asc? 
```ts
job.log('1')
job.log('2')
job.log('3')

getJobLogs(job.id, 0, -1, asc=true) === ['1', '2', '3']
getJobLogs(job.id, 0, -1, asc=false) === ['3', '2', '1']
```

2021-05-17 01:13 UTC, tjhiggins commented on src/classes/queue-getters.ts
> +      multi.lrange(logsKey, -(end + 1), -(start + 1));
I'm pretty sure this logic is incorrect for the opposite dir `multi.lrange(logsKey, -(end + 1), -(start + 1));`

```ts
job.log('1')
job.log('2')
job.log('3')

// actual
getJobLogs(job.id, 0, 1, asc=false) === ['2', '3']

// expected 
getJobLogs(job.id, 0, 1, asc=false) === ['3', '2']
```

Def add some test cases to confirm either way

2021-05-17 01:29 UTC, tjhiggins commented on src/classes/queue-getters.ts
> +      multi.lrange(logsKey, -(end + 1), -(start + 1));
Actually hold off on updating - asking Manuel for clarification on expected behavior
https://github.com/OptimalBits/bull/issues/2031#issuecomment-841917858

2021-05-17 01:37 UTC, roggervalf commented on src/classes/queue-getters.ts
> +      multi.lrange(logsKey, -(end + 1), -(start + 1));
hi @tjhiggins, yeah, actually, I based on the actual asc and desc implementation for lrange function call from https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-getters.ts#L130-L136, I guess this logic is here because lrange does not have a asc param, so just the indexes were changed, but still we should wait for @manast

2021-05-17 07:50 UTC, manast commented
I am re-studying the code since this was written long time ago and I did not remember it anymore. So basically the "asc" parameter is being used  in ```getRanges``` because depending on how the elements are inserted in the list, we need to lrange them differently to get them in the order we want, in other words, ```getRanges``` do not really support ascending or descending order its just telling it how to return the array items. 
For logs we put them in the list using "RPUSH", so they enter from the right side of the list. 
I also think the previous implementation of ```getLogs``` was wrong since it was not reversing the results for the descending case. So basically I think that what needs to be done is:
1) use ```multi.lrange(key, start, end);``` for the ASCENDING case, i.e. older logs first. (We consider it ascending since the log TIMESTAMP is increasing with time).
2) use ```multi.lrange(logsKey, -(end + 1), -(start + 1))```  and REVERSE the array before returning it for the DESCENDING case. i.e. newest logs first.
3) use ASCENDING as default (since the previous implementation was broken, this is actually the one that better matches the previous behaviour.

@roggervalf @tjhiggins let me know if this matches your expectations.

2021-05-17 11:34 UTC, tjhiggins commented
Agreed on all 3 points. Thanks for taking the time to dig in. I'll update the bull pr to reflect.

2021-05-18 07:55 UTC, merged