feat: add changedelay
taskforcesh/bullmq pull request #545
Opened 2021-05-13 11:47 UTC by wenq1

#543

2021-05-13 11:48 UTC, wenq1 commented
@manast  can you please review?

2021-05-13 14:15 UTC, roggervalf commented on src/commands/changeDelay-2.lua
> +
you also can add this validation https://github.com/taskforcesh/bullmq/blob/master/src/commands/getStateV2-7.lua#L31 so we are making sure that the job is in delayed state, if not maybe return -3 like in https://github.com/taskforcesh/bullmq/blob/master/src/commands/moveToDelayed-5.lua#L18 Job not in delayed state

2021-05-14 01:23 UTC, wenq1 commented on src/commands/changeDelay-2.lua
> +
OK

2021-05-14 01:36 UTC, wenq1 commented on src/commands/changeDelay-2.lua
> +
fixed below. also changed filename

2021-05-16 09:07 UTC, manast requested changes
Thanks for the PR. Please see my comments. Also it would be important to have at least one test that demonstrates it works.

2021-05-16 09:07 UTC, manast commented on src/commands/changeDelay-4.lua
> +   -1 - Job not in delayed set.
Maybe this should be -2

2021-05-16 09:07 UTC, manast commented on src/commands/changeDelay-4.lua
> +    return -3
return -2 ?

2021-05-16 09:07 UTC, manast commented on src/classes/job.ts
> +    (<any>multi).moveToDelayed(args);
Shouldn't we call the changeDelay script instead?

2021-05-16 09:07 UTC, manast commented on src/classes/job.ts
> +        throw Scripts.finishedErrors(code, this.id, command);
Since we have a new code expressing "missing job in delay set", finishedErrors will not be compatible.

2021-05-16 09:07 UTC, manast commented on src/classes/scripts.ts
> +    timestamp = typeof timestamp === 'undefined' ? 0 : timestamp;
The timestamp calculation is the same code we have in moveToDelayedArgs, it would be better to refactor that code, maybe a function called "calcDelayTimestamp" and use it in both places. Also note that the code for calculating the timestamp that you are using is old, you are probably basing your PR on an old version of the codebase.

2021-08-18 05:51 UTC, manast commented
Closing since functionality is already merged.

2021-08-18 05:51 UTC, closed without merging