Feat save worker info
taskforcesh/bullmq pull request #619
Opened 2021-06-28 04:06 UTC by roggervalf

This PR is just an idea following the comment in worker file, I would like to receive some feedback about it

2021-06-28 04:07 UTC, roggervalf commented on src/classes/worker.ts
> +    const workerKey = `${this.workerName}:${this.id}`;
should we consider a prefix in this key?

2021-07-05 10:25 UTC, manast requested changes

2021-07-05 10:25 UTC, manast commented on src/classes/queue-scheduler.ts
> +  private async workerCleaner(client: RedisClient) {
I think we can use one commando to achieve the same, namely https://redis.io/commands/zremrangebyscore so it can remove all the workers that are older than a given timestamp, simpler and more efficiently. Also use a const instead of 30000, ideally a configurable option.

2021-07-05 10:25 UTC, manast commented on src/classes/queue-scheduler.ts
> +    if (Number(timestamp) + 30000 < Date.now()) {
I think instead of 30000 it should be double of the time used when updating the worker.

2021-07-05 10:25 UTC, manast commented on src/classes/worker.ts
> +    let now = Date.now();
maybe a better name instead of now, "lastWorkerInfoUpdate" or something better.

2021-07-05 10:25 UTC, manast commented on src/classes/worker.ts
> +      if (Date.now() - now > 30000) {
reuse currentTime instead of calling Date.now() again.

2021-07-05 10:25 UTC, manast commented on src/classes/worker.ts
> +      if (Date.now() - now > 30000) {
parametrize 30000 as a worker option

2021-07-05 10:25 UTC, manast commented on src/classes/worker.ts
> +    multi.zadd(this.keys.workers, now, workerKey);
what if instead of using a new key we just store the info as a json object in the zset? that would also simplify deletion logic.

2021-07-12 13:19 UTC, manast commented on src/classes/worker.ts
> +      if (currentTime - lastWorkerInfoUpdate > 30000) {
This 30000 must be somehow "syched" with workerCleanerTimeout in queue scheduler for this mechanism to work properly.

2021-07-22 13:27 UTC, manast commented on src/classes/worker.ts
> +    multi.zadd(this.keys.workers, now, workerKey);
I was probably tired when I wrote this, of course my suggestion above is not possible at all.
Just trying to figure out how we could solve this so that QueueScheduler and Worker do not need to work in sync for this feature to work.

2021-07-22 13:27 UTC, manast commented on src/classes/worker.ts
> +    multi.expire(workerKey, 30);
this expire is not so useful since we still need to delete the worker key from the workers set or the two data structures will be off-sync

2021-07-25 22:54 UTC, roggervalf commented
I'm still thinking how to address some comments

2021-07-25 23:01 UTC, manast commented
> I'm still thinking how to address some comments

will try to give you more feedback as soon as I get some extra time...

2021-07-25 23:13 UTC, roggervalf commented
> will try to give you more feedback as soon as I get some extra time...

no worries, I was notified that it is still in progress status

2021-11-05 02:03 UTC, merged

2021-11-05 02:11 UTC, roggervalf commented
This feature was moved to another updated branch

2021-11-12 05:25 UTC, manast commented
So basically we are back to square one. But the major advantage of using client setname/list is that we do not need to manually keep updating which worker is currently alive or not... sorry for leading you in the wrong direction when we discussed this issue the other day.