Feat parent opts in root job for a flow
taskforcesh/bullmq pull request #630
Opened 2021-07-06 01:57 UTC by roggervalf

This PR allows to add parent opts for a root job in a flow, it makes sense only allow this for the first parent job since children are concatenated into their parents so children should not have this option, this option is generated by add flow method.

2021-07-06 08:44 UTC, manast requested changes

2021-07-06 08:44 UTC, manast commented on src/interfaces/flow-job.ts
> +  children?: FlowChildJob[];
We could refactor these two almost identical interfaces. Two approaches comes to mind, either define a base interface with the common properties and have to especialized interfaces extending from it, or create a generic, where the opts type is passed when defining the concrete interfaces, I think this can be done:
```ts
interface FlowJobBase<T> {
  name: string;
  queueName: string;
  data?: any;
  prefix?: string;
  opts?: T;
  children?: FlowChildJob[];
}

export type FlowChildJob = FlowJobBase<Omit<JobsOptions, 'parent'>>;
export type FlowJob = FlowJobBase<JobsOptions>>;
```

2021-07-06 08:44 UTC, manast commented on src/classes/flow-producer.ts
> +    const parentOpts = flow?.opts?.parent;
what about just adding an extra optional parameter to "add" instead of passing the parent options in the FlowJob interface?

2021-07-07 00:46 UTC, roggervalf commented on src/classes/flow-producer.ts
> +    const parentOpts = flow?.opts?.parent;
I'm thinking on the addBulk method https://github.com/taskforcesh/bullmq/pull/542, maybe would be expected to create flows with different parents too, what do you think?

2021-08-06 12:09 UTC, manast commented on src/test/test_flow.ts
> +  it('should allow parent opts on the root job', async () => {
The part that still intrigues me is how this is handle in a real life scenario where I assume there would be a grandparent worker which currently would not wait for the parentJob to be created so that the grandparent will wait for it to complete... I apologize if I miss something obvious🙏

2021-08-08 04:03 UTC, roggervalf commented on src/test/test_flow.ts
> +  it('should allow parent opts on the root job', async () => {
I was thinking on this scenario and now that that you mention this, I think it would have more sense to use it in manual processing since the grandparent should not have a good way to wait for the parentJob in the test case that I did. Maybe this pr could wait until we get the feature of waiting children from function processors.

2022-03-02 00:41 UTC, merged