Feat add bulk flow jobs
taskforcesh/bullmq pull request #674
Opened 2021-08-04 14:11 UTC by Stormtv

Adding bulk FlowJobs is a nice to have when adding multiple Flows at once. I attempted to change the least amount of code possible to make this happen.

Sorry for the delay in doing this PR but this should be cleaner than the last one #542. Let me know if there are any changes you would suggest.

2021-08-06 14:29 UTC, manast requested changes
Looks great, please check my comments.

2021-08-06 14:29 UTC, manast commented on src/test/test_flow.ts
> +  it('should process job when using addBulk', async () => {
typo: job -> jobs

2021-08-06 14:29 UTC, manast commented on src/classes/flow-producer.ts
> +    const updateJobIds = (jobTree: JobNode) => {
I think you can refactor the ```updateJobIds``` function and change it so that it returns the index and so you can call it for every "jobTree" and avoid the duplication of code. So the loop will become something like this:
```ts
   let index = 0;
   for (const jobTree of jobsTrees) {
      index = updateJobIds(jobTree, result, index);
    }
```

2021-08-09 22:56 UTC, Stormtv commented on src/classes/flow-producer.ts
> +    const updateJobIds = (jobTree: JobNode) => {
Pushed up a refactor for this good call

2021-08-18 06:31 UTC, manast commented on src/classes/flow-producer.ts
> +      for (let i = 0; i < children.length; i++) {
After writing this comment I realized that updateIds is not really necessary since the jobs have already the ids before being added to the queue as they are generated with a uuid, so I removed this code and made a PR: https://github.com/taskforcesh/bullmq/pull/684
So unless I have missed something you can also do the same in your PR.

2021-08-18 18:10 UTC, Stormtv commented
@manast I merged the changes and removed the update job ids but the precommit script seemed to have linted some of the other files.

2021-08-20 02:10 UTC, manast commented
I removed the changes in changelog and merged it in this PR instead, thanks for the contribution!
https://github.com/taskforcesh/bullmq/pull/690

2021-08-20 02:10 UTC, closed without merging