Docs: apply jsdoc
taskforcesh/bullmq pull request #695
Opened 2021-08-21 01:40 UTC by roggervalf

This pr adds some jsdoc sentences and fix some others

2021-08-21 06:16 UTC, manast requested changes

2021-08-21 06:16 UTC, manast commented on .gitignore
> +package-lock.json
I think we need to keep package-lock.json for users that do not use yarn.

2021-08-23 03:02 UTC, roggervalf commented on .gitignore
> +package-lock.json
![Selection_042](https://user-images.githubusercontent.com/14021523/130384137-449bec64-4587-4f30-a832-aa3441079db8.png)
I used npm in windows but it seems that when using yarn, then appears this warning, also our scripts are using yarn, I can still delete line 23, but what do you think?

2021-08-23 06:35 UTC, manast commented on .gitignore
> +package-lock.json
In that case we must recommend yarn as the tool to install BullMQ... in any case this is not so important since package-lock and yarn.lock are only used when developing BullMQ but not when using it as a dependency.

2021-08-23 06:35 UTC, merged