feat(worker): launch without launching process
taskforcesh/bullmq pull request #724
Opened 2021-08-31 02:23 UTC by roggervalf

re #436

2021-08-31 07:59 UTC, manast requested changes
Good that you fixed this issue! Please check the comments.

2021-08-31 07:59 UTC, manast commented on src/classes/worker.ts
> +      process: true,
I think "autorun" is a good name here actually.

2021-08-31 07:59 UTC, manast commented on src/classes/worker.ts
> +  process(): void {
I think we can just make "run" public, so the error handling will be taken care by the caller. And inside the run() function we could just throw an exception if processFn is not defined (as it does not make sense to start the run loop if no process function is defined.

2021-09-01 00:44 UTC, roggervalf commented on src/classes/worker.ts
> +  process(): void {
sure, let me refactor it a little bit

2021-09-02 03:20 UTC, manast reviewed
Looks good. I think you should squeeze this PR and use "feat" since you are adding a new feature.

2021-09-02 13:50 UTC, merged